name: SpacePush
on: [push]
env: 
  SPACE_ACCESS_TOKEN: ${{ secrets.SPACE_SECRET }}
jobs:
  deploy:
      name: Push to space
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - id: space_cli
          run: |
            curl -fsSL https://get.deta.dev/space-cli.sh | sh
            echo '/home/runner/.detaspace/bin' >> $GITHUB_PATH
        - id: deploy
          shell: script -q -e -c "bash {0}"
          run: space push -i ${{ secrets.PROJECT_ID }}